#!/bin/sh

clear

#git push --set-upstream origin dev
#git push --set-upstream origin feature/login
git push --set-upstream origin viviane-florido-project-react-testing-library

git add .
git commit -am "update"
git push

exit 0
